CREATE TABLE tbl_message(
	NO 		  	  INT 			   AUTO_INCREMENT PRIMARY KEY,
	NAME 			  VARCHAR(50)  NULL,
	EMAIL 		  VARCHAR(50)  NOT NULL,
	MESSAGE 		VARCHAR(200) NUll,
	CREATE_DATE DATETIME 	   DEFAULT CURRENT_TIMESTAMP() null
);
